# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [6]:
print(np.__version__)
print(np.show_config())

2.0.0
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.10",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.27",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-tag2k3sw/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib 

c:\Python311\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10 (★☆☆)

In [37]:
a= np.arange(10)
b = np.arange(2, 10, dtype=float)
c = np.arange(2, 3, 0.1)
print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[2. 3. 4. 5. 6. 7. 8. 9.]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


#### 4. How to find the memory size of any array (★☆☆)

In [8]:
# a.itemsize * a.size
a.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [9]:
# python -c "import numpy; numpy.info(numpy.add)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
a = np.arange(10, 50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
b = np.flip(a)
print(b)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
aaa = np.arange(0, 9).reshape(3,3)
print(aaa)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [14]:
a = np.nonzero([1, 2, 0, 0, 4, 0])
print(a)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [15]:
a = np.eye(3, 3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [8]:
a = np.random.rand(3, 3)
print(a)

[[0.36579996 0.07882481 0.58653955]
 [0.636327   0.28562583 0.60541892]
 [0.53409758 0.49623717 0.56719793]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [17]:
a = np.random.rand(10, 10)
max = np.max(a)
min = np.min(a)
print(a)
print(max, min)

[[0.07164693 0.44734118 0.30879966 0.52835257 0.26478305 0.57815843
  0.9441422  0.33812291 0.06677554 0.55844956]
 [0.70958409 0.65099299 0.16138024 0.44359342 0.34873683 0.89002397
  0.33602706 0.97303212 0.86390012 0.60605743]
 [0.61563307 0.70231341 0.84429317 0.773091   0.2233887  0.78751683
  0.59888429 0.66445975 0.27751311 0.37959691]
 [0.0292162  0.33329187 0.9381637  0.46396963 0.12123153 0.26214718
  0.14098374 0.03719762 0.66897411 0.63677568]
 [0.38183757 0.60677371 0.21562922 0.23924644 0.11399312 0.09387575
  0.31481305 0.63286147 0.33847258 0.26955223]
 [0.0916603  0.32656819 0.16441831 0.87659299 0.69915702 0.38775884
  0.3924528  0.3824729  0.03478016 0.11242628]
 [0.76855436 0.48023306 0.19975817 0.40970085 0.25773781 0.7134033
  0.71964075 0.87741838 0.66577366 0.9503362 ]
 [0.39568445 0.00976937 0.83075459 0.72195994 0.59467142 0.80578195
  0.70278976 0.75994174 0.38684285 0.31623796]
 [0.10940063 0.19077118 0.43198248 0.84095637 0.37442654 0.2860217
  0.50715146 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
a = np.random.rand(30)
print(a)
print(np.average(a))

[0.48803997 0.07152053 0.54276023 0.65576345 0.57022677 0.49237682
 0.34588375 0.88013487 0.06103228 0.76507785 0.4785074  0.15953335
 0.64887655 0.52912074 0.54093827 0.10240919 0.78022125 0.19452102
 0.71289177 0.1224666  0.31946685 0.86789003 0.27450703 0.51245234
 0.51417444 0.67051557 0.38986092 0.80727117 0.77036316 0.02878726]
0.47658638170272505


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [19]:
a = np.ones((5,5))
a[1: -1, 1: -1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [20]:
a = np.ones((3, 3))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [21]:
print(np.nan)
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.inf - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == (3 * 0.1))

nan
nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [22]:
a= np.diag(np.arange(1, 5), k=-1)
print(a)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [41]:
a = np.ones((8, 8))
a[1::2, ::2] = 0
a[0::2, 1::2] = 0

print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [42]:
a = np.unravel_index(100, (6, 7, 8))
print(a)

(np.int64(1), np.int64(5), np.int64(4))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [47]:
a = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [49]:
a = np.random.random((5, 5))
print(a)
max, min = a.max(), a.min()
a = (a - min) / (max - min)
print(a)

[[0.04608402 0.05257819 0.01673125 0.7974941  0.28023261]
 [0.03959436 0.12484747 0.6263541  0.92341426 0.37917909]
 [0.6882551  0.35647664 0.10956878 0.82663416 0.81296134]
 [0.25732811 0.54096967 0.77876824 0.57240502 0.42564266]
 [0.4829457  0.78345581 0.22151596 0.6988046  0.32568867]]
[[0.0323738  0.03953635 0.         0.86111997 0.29062127]
 [0.02521622 0.11924368 0.67236603 1.         0.39975144]
 [0.74063795 0.37471242 0.10239249 0.89325916 0.87817912]
 [0.2653594  0.57819372 0.84046682 0.61286443 0.4509971 ]
 [0.51419784 0.84563684 0.22586142 0.75227323 0.34075572]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [10]:
a = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])
print(a)


[('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [12]:
b = np.ones((5,3))
print(b)
bb = np.ones((3,2))
print(bb)

a = np.dot(b, bb)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [16]:
a = np.arange(11)
print(a)
# a *= -1
a[(3 < a) & (a <= 8)] *= -1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [33]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [39]:
a = np.ones((1, 3))
b = np.arange(4)
print(a)
print(b)

# print(a**b)

[[1. 1. 1.]]
[0 1 2 3]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [40]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\junai\AppData\Local\Temp\ipykernel_24984\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\junai\AppData\Local\Temp\ipykernel_24984\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\junai\AppData\Local\Temp\ipykernel_24984\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [47]:
a = np.random.uniform(0, 10, 5)
print(a)


[8.56312405 6.74980028 3.21837375 5.41445579 5.60177917]


#### 30. How to find common values between two arrays? (★☆☆)

In [3]:
a1 = np.array([0, 10, 20, 40, 60])
a2 = np.array([0, 3, 4, 20, 50])
b = np.intersect1d(a1, a2)
print(b)

[ 0 20]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [4]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [7]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
print(np.sqrt(-1) == np.emath.sqrt(-1))
print(np.sqrt(4))
print(np.emath.sqrt(4))
print(np.sqrt(4) == np.emath.sqrt(4))



nan
1j
False
2.0
2.0
True


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [10]:
today = np.datetime64('today', 'D')
print(today) 
y = today - np.timedelta64(1, 'D')
print(y)
tom = today + np.timedelta64(1, 'D')
print(tom)


2024-06-23
2024-06-22
2024-06-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [22]:
a = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [15]:
a = np.arange(9).reshape(3, 3)
b = np.transpose(a)
print(a)
print(b)
print(a + b)
c = ((a + b) * (-a / 2))
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[ 0  4  8]
 [ 4  8 12]
 [ 8 12 16]]
[[  0.  -2.  -8.]
 [ -6. -16. -30.]
 [-24. -42. -64.]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [29]:
a = np.random.uniform(0, 10, 10)
print(a)

print(a - a % 1)
print(a // 1)
print(np.floor(a))
print(a.astype(int))

[9.1025023  1.2266121  7.770707   6.31951115 7.51966375 5.09007951
 9.65891869 0.79395323 4.51428096 1.38869892]
[9. 1. 7. 6. 7. 5. 9. 0. 4. 1.]
[9. 1. 7. 6. 7. 5. 9. 0. 4. 1.]
[9. 1. 7. 6. 7. 5. 9. 0. 4. 1.]
[9 1 7 6 7 5 9 0 4 1]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [35]:
a = np.zeros((5, 5))
print(a)
a += np.arange(5)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [50]:
print(np.arange(10))

def generate():
    for i in range(10):
        yield i

z = np.fromiter(generate(), dtype=int)
print(z)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [61]:
a = np.linspace(0, 1, 12, endpoint=True)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [64]:
a = np.random.random(10)
a.sort()
print(a)

[0.01552417 0.09020855 0.11224978 0.11334728 0.11735938 0.35284464
 0.44697004 0.82792475 0.8433248  0.98938731]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [68]:
a = np.arange(10)
print(np.sum(a))

s = np.add.reduce(a)
print(s)

45
45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [6]:
a = np.random.randint(0, 2, 6)
print(a)
b = np.random.randint(0, 2, 6)
print(b)
array_equal = np.allclose(a, b)
print(array_equal)


[1 1 1 0 0 1]
[0 0 1 1 1 1]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [14]:
a = np.arange(1, 20)
a.flags.writeable = False
print(a)
a[0] = 0

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [24]:
a = np.random.random((10, 2))
x, y = a[:, 0], a[:, 1]
r = np.sqrt(x ** 2 + y ** 2)
t = np.arctan2(y, x)

print(a)
print(x)
print(y)
print(r)
print(t)

[[0.00782519 0.63684568]
 [0.7771504  0.38148427]
 [0.21459969 0.9872775 ]
 [0.88376452 0.18222796]
 [0.24833926 0.73226961]
 [0.26521024 0.77170515]
 [0.53022672 0.57597293]
 [0.70752288 0.10353633]
 [0.53427362 0.29075655]
 [0.87391513 0.89742083]]
[0.00782519 0.7771504  0.21459969 0.88376452 0.24833926 0.26521024
 0.53022672 0.70752288 0.53427362 0.87391513]
[0.63684568 0.38148427 0.9872775  0.18222796 0.73226961 0.77170515
 0.57597293 0.10353633 0.29075655 0.89742083]
[0.63689376 0.86573264 1.01033158 0.90235622 0.77323423 0.8160057
 0.78286984 0.71505831 0.60826612 1.25263395]
[1.55850952 0.45632158 1.35676065 0.20334527 1.24383216 1.23977373
 0.826729   0.14530502 0.49838634 0.79866742]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [27]:
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.38999129 0.73351684 0.53156254 0.16643033 0.31783464 0.6419599
 0.078897   0.         0.6074677  0.81335316]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [35]:
a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)