### 101 NumPy Exercises for Data Analysis (Python)

### Questions from https://www.machinelearningplus.com/python/101-numpy-exercises-python/


Difficulty Level: L1
Q. Import numpy as np and print the version number.

In [4]:
import numpy as np
print(np.__version__)

2.0.0


Difficulty Level: L1

Q. Create a 1D array of numbers from 0 to 9

In [2]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


Difficulty Level: L1

Q. Create a 3×3 numpy array of all True’s

In [10]:
a = np.full((3,3), True, dtype=bool)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Difficulty Level: L1

Q. Extract all odd numbers from arr

In [18]:
a = np.arange(10)
a = a[a % 2 == 1]
print(a)

[1 3 5 7 9]


Difficulty Level: L1

Q. Replace all odd numbers in arr with -1

Input:

In [14]:
a = np.arange(10)
a[a % 2 == 1] = -1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Difficulty Level: L2

Q. Replace all odd numbers in arr with -1 without changing arr

Input:

In [27]:
a = np.arange(10)
print(a)
b = np.where(a % 2 == 1, -1, a)
print(b)
# c = np.array(b)
# print(c)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Difficulty Level: L1

Q. Convert a 1D array to a 2D array with 2 rows

In [32]:
a = np.arange(10)
a = a.reshape((2, 5))
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Difficulty Level: L2

Q. Stack arrays a and b vertically

In [53]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
# c = np.full((1, 10), 1)[0]
print(a)
print(b)
c = np.vstack([a, b])
print(c)


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Difficulty Level: L2

Q. Stack the arrays a and b horizontally.

Input

In [54]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

c = np.hstack([a, b])
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


Difficulty Level: L2

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

In [58]:
a = np.array([1, 2, 3])

one = np.repeat(a[0], 3)
two = np.repeat(a[1], 3)
three = np.repeat(a[2], 3)

b = np.hstack([one, two, three, a, a, a])
print(b)

c = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(c)


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
