### 101 NumPy Exercises for Data Analysis (Python)

### Questions from https://www.machinelearningplus.com/python/101-numpy-exercises-python/


Difficulty Level: L1
Q. Import numpy as np and print the version number.

In [31]:
import numpy as np
print(np.__version__)

2.0.0


Difficulty Level: L1

Q. Create a 1D array of numbers from 0 to 9

In [2]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


Difficulty Level: L1

Q. Create a 3×3 numpy array of all True’s

In [10]:
a = np.full((3,3), True, dtype=bool)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Difficulty Level: L1

Q. Extract all odd numbers from arr

In [18]:
a = np.arange(10)
a = a[a % 2 == 1]
print(a)

[1 3 5 7 9]


Difficulty Level: L1

Q. Replace all odd numbers in arr with -1

Input:

In [14]:
a = np.arange(10)
a[a % 2 == 1] = -1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Difficulty Level: L2

Q. Replace all odd numbers in arr with -1 without changing arr

Input:

In [27]:
a = np.arange(10)
print(a)
b = np.where(a % 2 == 1, -1, a)
print(b)
# c = np.array(b)
# print(c)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Difficulty Level: L1

Q. Convert a 1D array to a 2D array with 2 rows

In [32]:
a = np.arange(10)
a = a.reshape((2, 5))
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Difficulty Level: L2

Q. Stack arrays a and b vertically

In [53]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
# c = np.full((1, 10), 1)[0]
print(a)
print(b)
c = np.vstack([a, b])
print(c)


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Difficulty Level: L2

Q. Stack the arrays a and b horizontally.

Input

In [54]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

c = np.hstack([a, b])
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


Difficulty Level: L2

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

In [58]:
a = np.array([1, 2, 3])

one = np.repeat(a[0], 3)
two = np.repeat(a[1], 3)
three = np.repeat(a[2], 3)

b = np.hstack([one, two, three, a, a, a])
print(b)

c = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(c)


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


Difficulty Level: L2

Q. Get the common items between a and b

Input:

In [63]:
a = np.arange(10)
b = np.arange(5, 10)
c = np.intersect1d(a, b)
print(c)

[5 6 7 8 9]


Difficulty Level: L2

Q. From array a remove all items present in array b
Input:

In [64]:
a = np.arange(10)
b = np.arange(5, 10)
c = np.setdiff1d(a, b)
print(c)

[0 1 2 3 4]


Difficulty Level: L2

Q. Get the positions where elements of a and b match

In [68]:
a = np.arange(10)
b = np.arange(5, 15)
print(a)
print(b)
np.where(a == b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[0 1 2 3 4]


14. Difficulty Level: L2

Q. Get all items between 5 and 10 from a.

Input:

In [80]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

index = np.where((a >= 5) & (a <= 10))
print(a[b])

c = a[(a >=5) & (a <= 10)]
print(c)

[ 6  9 10]
[ 6  9 10]


15. Difficulty Level: L2

Q. Convert the function maxx that works on two scalars, to work on two arrays.

In [9]:
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y


c = np.vectorize(maxx, otypes=[float])
a = np.random.randint(0, 10, 10, dtype=int)
b = np.random.randint(5, 10, 10, dtype=int)
print(a)
print(b)
print(c(a, b))



[3 2 8 1 6 3 9 1 1 0]
[5 7 6 6 7 6 5 8 9 7]
[5. 7. 8. 6. 7. 6. 9. 8. 9. 7.]


16. How to swap two columns in a 2d numpy array?
Difficulty Level: L2

Q. Swap columns 1 and 2 in the array arr.

In [18]:
a = np.random.randint(0, 10, 9, dtype=int)
a = a.reshape((3, -1))
print(a)
print(a[:, [0, 2, 1]])



[[2 0 3]
 [5 8 8]
 [9 6 8]]
[[2 3 0]
 [5 8 8]
 [9 8 6]]


17. How to swap two rows in a 2d numpy array?
Difficulty Level: L2

Q. Swap rows 1 and 2 in the array arr:

In [22]:
a = np.random.randint(0, 9, 9, dtype=int)
a = a.reshape(3, 3)
print(a)
a = a[[0, 2, 1], :]
print(a)

[[8 0 7]
 [8 8 1]
 [1 1 0]]
[[8 0 7]
 [1 1 0]
 [8 8 1]]


18. How to reverse the rows of a 2D array?
Difficulty Level: L2

Q. Reverse the rows of a 2D array arr.

In [31]:
a = np.random.randint(0, 20, 9, dtype=int).reshape(3, 3)
print(a)
a = a[:: -1]
print(a)


[[10  8  1]
 [ 7 17 18]
 [18 12  6]]
[[18 12  6]
 [ 7 17 18]
 [10  8  1]]


19. How to reverse the columns of a 2D array?
Difficulty Level: L2

Q. Reverse the columns of a 2D array arr.

In [34]:
a = np.arange(9).reshape(3, 3)
print(a)
a = a[:, :: -1]
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


20. How to create a 2D array containing random floats between 5 and 10?
Difficulty Level: L2
Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [36]:
a = np.random.uniform(5, 10, size=(5,3))
print(a)

[[7.70934808 8.79737064 9.67666104]
 [7.32756873 9.37922642 7.36714488]
 [7.08288696 9.39102651 5.07460962]
 [8.83385438 7.16089669 7.05689459]
 [7.98133458 7.65311798 8.8891074 ]]


21. How to print only 3 decimal places in python numpy array?
Difficulty Level: L1

Q. Print or show only 3 decimal places of the numpy array rand_arr.
Input:

In [9]:
a = np.random.random((5, 3))
np.set_printoptions(precision=3)
print(a)


[[0.912 0.132 0.69 ]
 [0.438 0.116 0.722]
 [0.892 0.545 0.444]
 [0.693 0.631 0.659]
 [0.359 0.578 0.493]]


22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
Difficulty Level: L1

Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

In [22]:
a = np.random.seed(100)
b = np.random.random([3, 3])/1e3
np.set_printoptions(suppress=True, precision=6)
print(b)

[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


23. How to limit the number of items printed in output of numpy array?
Difficulty Level: L1

Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [24]:
a = np.arange(15)
np.set_printoptions(threshold = 6)
print(a)

[ 0  1  2 ... 12 13 14]


24. How to print the full numpy array without truncating
Difficulty Level: L1

Q. Print the full numpy array a without truncating.

In [30]:
a = np.arange(15)
np.set_printoptions(threshold = 15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
Difficulty Level: L2

Q. Import the iris dataset keeping the text intact.

In [32]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print([iris[:3]])

[array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)]


26. How to extract a particular column from 1D array of tuples?
Difficulty Level: L2

Q. Extract the text column species from the 1D iris imported in previous question.

In [73]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)
print(iris_1d)
print('fifth row')
print(iris_1d[4])

species = np.array([row[4] for row in iris_1d])
print(species)
# print(species[:5])


(150,)
[(5.1, 3.5, 1.4, 0.2, 'Iris-setosa') (4.9, 3. , 1.4, 0.2, 'Iris-setosa')
 (4.7, 3.2, 1.3, 0.2, 'Iris-setosa') ...
 (6.5, 3. , 5.2, 2. , 'Iris-virginica')
 (6.2, 3.4, 5.4, 2.3, 'Iris-virginica')
 (5.9, 3. , 5.1, 1.8, 'Iris-virginica')]
fifth row
(5.0, 3.6, 1.4, 0.2, 'Iris-setosa')
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' ... 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica']


27. How to convert a 1d array of tuples to a 2d numpy array?
Difficulty Level: L2

Q. Convert the 1D iris to 2D array iris_2d by omitting the species text field.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]
