### 101 NumPy Exercises for Data Analysis (Python)

### Questions from https://www.machinelearningplus.com/python/101-numpy-exercises-python/


Difficulty Level: L1
Q. Import numpy as np and print the version number.

In [2]:
import numpy as np
print(np.__version__)

2.0.0


Difficulty Level: L1

Q. Create a 1D array of numbers from 0 to 9

In [2]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


Difficulty Level: L1

Q. Create a 3×3 numpy array of all True’s

In [10]:
a = np.full((3,3), True, dtype=bool)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Difficulty Level: L1

Q. Extract all odd numbers from arr

In [18]:
a = np.arange(10)
a = a[a % 2 == 1]
print(a)

[1 3 5 7 9]


Difficulty Level: L1

Q. Replace all odd numbers in arr with -1

Input:

In [14]:
a = np.arange(10)
a[a % 2 == 1] = -1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Difficulty Level: L2

Q. Replace all odd numbers in arr with -1 without changing arr

Input:

In [27]:
a = np.arange(10)
print(a)
b = np.where(a % 2 == 1, -1, a)
print(b)
# c = np.array(b)
# print(c)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Difficulty Level: L1

Q. Convert a 1D array to a 2D array with 2 rows

In [32]:
a = np.arange(10)
a = a.reshape((2, 5))
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Difficulty Level: L2

Q. Stack arrays a and b vertically

In [53]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
# c = np.full((1, 10), 1)[0]
print(a)
print(b)
c = np.vstack([a, b])
print(c)


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Difficulty Level: L2

Q. Stack the arrays a and b horizontally.

Input

In [54]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

c = np.hstack([a, b])
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


Difficulty Level: L2

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

In [58]:
a = np.array([1, 2, 3])

one = np.repeat(a[0], 3)
two = np.repeat(a[1], 3)
three = np.repeat(a[2], 3)

b = np.hstack([one, two, three, a, a, a])
print(b)

c = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(c)


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


Difficulty Level: L2

Q. Get the common items between a and b

Input:

In [63]:
a = np.arange(10)
b = np.arange(5, 10)
c = np.intersect1d(a, b)
print(c)

[5 6 7 8 9]


Difficulty Level: L2

Q. From array a remove all items present in array b
Input:

In [64]:
a = np.arange(10)
b = np.arange(5, 10)
c = np.setdiff1d(a, b)
print(c)

[0 1 2 3 4]


Difficulty Level: L2

Q. Get the positions where elements of a and b match

In [68]:
a = np.arange(10)
b = np.arange(5, 15)
print(a)
print(b)
np.where(a == b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[0 1 2 3 4]


14. Difficulty Level: L2

Q. Get all items between 5 and 10 from a.

Input:

In [80]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

index = np.where((a >= 5) & (a <= 10))
print(a[b])

c = a[(a >=5) & (a <= 10)]
print(c)

[ 6  9 10]
[ 6  9 10]


15. Difficulty Level: L2

Q. Convert the function maxx that works on two scalars, to work on two arrays.

In [9]:
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y


c = np.vectorize(maxx, otypes=[float])
a = np.random.randint(0, 10, 10, dtype=int)
b = np.random.randint(5, 10, 10, dtype=int)
print(a)
print(b)
print(c(a, b))



[3 2 8 1 6 3 9 1 1 0]
[5 7 6 6 7 6 5 8 9 7]
[5. 7. 8. 6. 7. 6. 9. 8. 9. 7.]


16. How to swap two columns in a 2d numpy array?
Difficulty Level: L2

Q. Swap columns 1 and 2 in the array arr.

In [18]:
a = np.random.randint(0, 10, 9, dtype=int)
a = a.reshape((3, -1))
print(a)
print(a[:, [0, 2, 1]])



[[2 0 3]
 [5 8 8]
 [9 6 8]]
[[2 3 0]
 [5 8 8]
 [9 8 6]]


17. How to swap two rows in a 2d numpy array?
Difficulty Level: L2

Q. Swap rows 1 and 2 in the array arr:

In [22]:
a = np.random.randint(0, 9, 9, dtype=int)
a = a.reshape(3, 3)
print(a)
a = a[[0, 2, 1], :]
print(a)

[[8 0 7]
 [8 8 1]
 [1 1 0]]
[[8 0 7]
 [1 1 0]
 [8 8 1]]


18. How to reverse the rows of a 2D array?
Difficulty Level: L2

Q. Reverse the rows of a 2D array arr.

In [31]:
a = np.random.randint(0, 20, 9, dtype=int).reshape(3, 3)
print(a)
a = a[:: -1]
print(a)


[[10  8  1]
 [ 7 17 18]
 [18 12  6]]
[[18 12  6]
 [ 7 17 18]
 [10  8  1]]


19. How to reverse the columns of a 2D array?
Difficulty Level: L2

Q. Reverse the columns of a 2D array arr.

In [34]:
a = np.arange(9).reshape(3, 3)
print(a)
a = a[:, :: -1]
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


20. How to create a 2D array containing random floats between 5 and 10?
Difficulty Level: L2
Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [36]:
a = np.random.uniform(5, 10, size=(5,3))
print(a)

[[7.70934808 8.79737064 9.67666104]
 [7.32756873 9.37922642 7.36714488]
 [7.08288696 9.39102651 5.07460962]
 [8.83385438 7.16089669 7.05689459]
 [7.98133458 7.65311798 8.8891074 ]]


21. How to print only 3 decimal places in python numpy array?
Difficulty Level: L1

Q. Print or show only 3 decimal places of the numpy array rand_arr.
Input:

In [9]:
a = np.random.random((5, 3))
np.set_printoptions(precision=3)
print(a)


[[0.912 0.132 0.69 ]
 [0.438 0.116 0.722]
 [0.892 0.545 0.444]
 [0.693 0.631 0.659]
 [0.359 0.578 0.493]]


22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
Difficulty Level: L1

Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

In [22]:
a = np.random.seed(100)
b = np.random.random([3, 3])/1e3
np.set_printoptions(suppress=True, precision=6)
print(b)

[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


23. How to limit the number of items printed in output of numpy array?
Difficulty Level: L1

Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [24]:
a = np.arange(15)
np.set_printoptions(threshold = 6)
print(a)

[ 0  1  2 ... 12 13 14]


24. How to print the full numpy array without truncating
Difficulty Level: L1

Q. Print the full numpy array a without truncating.

In [30]:
a = np.arange(15)
np.set_printoptions(threshold = 15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
Difficulty Level: L2

Q. Import the iris dataset keeping the text intact.

In [32]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print([iris[:3]])

[array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)]


26. How to extract a particular column from 1D array of tuples?
Difficulty Level: L2

Q. Extract the text column species from the 1D iris imported in previous question.

In [73]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)
print(iris_1d)
print('fifth row')
print(iris_1d[4])

species = np.array([row[4] for row in iris_1d])
print(species)
# print(species[:5])


(150,)
[(5.1, 3.5, 1.4, 0.2, 'Iris-setosa') (4.9, 3. , 1.4, 0.2, 'Iris-setosa')
 (4.7, 3.2, 1.3, 0.2, 'Iris-setosa') ...
 (6.5, 3. , 5.2, 2. , 'Iris-virginica')
 (6.2, 3.4, 5.4, 2.3, 'Iris-virginica')
 (5.9, 3. , 5.1, 1.8, 'Iris-virginica')]
fifth row
(5.0, 3.6, 1.4, 0.2, 'Iris-setosa')
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' ... 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica']


27. How to convert a 1d array of tuples to a 2d numpy array?
Difficulty Level: L2

Q. Convert the 1D iris to 2D array iris_2d by omitting the species text field.

In [7]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
print('iris_2d')
print(iris_2d)
#iris_2d[:4]


iris_2d
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.

28. How to compute the mean, median, standard deviation of a numpy array?
Difficulty: L1
Q. Find the mean, median, standard deviation of iris's sepallength (1st column)

In [16]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
print(sepallength)

mu = np.mean(sepallength)
med = np.median(sepallength)
sd = np.std(sepallength)

print(mu, med, sd)



[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]
5.843333333333334 5.8 0.8253012917851409


29. How to normalize an array so the values range exactly between 0 and 1?
Difficulty: L2

Q. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

In [17]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

max = sepallength.max()
min = sepallength.min()

S = (sepallength - min) / (max - min)
print(S)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

30. How to compute the softmax score?
Difficulty Level: L3

Q. Compute the softmax score of sepallength.

In [18]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

print(softmax(sepallength))


[0.00221959 0.00181724 0.00148783 0.00134625 0.00200836 0.00299613
 0.00134625 0.00200836 0.00110221 0.00181724 0.00299613 0.00164431
 0.00164431 0.00099732 0.0044697  0.00404435 0.00299613 0.00221959
 0.00404435 0.00221959 0.00299613 0.00221959 0.00134625 0.00221959
 0.00164431 0.00200836 0.00200836 0.00245302 0.00245302 0.00148783
 0.00164431 0.00299613 0.00245302 0.00331123 0.00181724 0.00200836
 0.00331123 0.00181724 0.00110221 0.00221959 0.00200836 0.00121813
 0.00110221 0.00200836 0.00221959 0.00164431 0.00221959 0.00134625
 0.00271101 0.00200836 0.01483991 0.00814432 0.01342771 0.00331123
 0.00900086 0.00404435 0.00736928 0.00181724 0.00994749 0.00245302
 0.00200836 0.00493978 0.0054593  0.00603346 0.00365948 0.01099368
 0.00365948 0.0044697  0.006668   0.00365948 0.00493978 0.00603346
 0.00736928 0.00603346 0.00814432 0.00994749 0.01214989 0.01099368
 0.0054593  0.00404435 0.00331123 0.00331123 0.0044697  0.0054593
 0.00299613 0.0054593  0.01099368 0.00736928 0.00365948 0.00331

31. How to find the percentile scores of a numpy array?
Difficulty Level: L1

Q. Find the 5th and 95th percentile of iris's sepallength

In [19]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

a = np.percentile(sepallength, q=[5, 95])
print(a)

[4.6   7.255]


32. How to insert values at random positions in an array?
Difficulty Level: L2

Q. Insert np.nan values at 20 random positions in iris_2d dataset

In [5]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

a = np.random.seed(100)
print(np.random.randint(150, size=20))
print(np.random.randint(4, size = 20))
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size = 20)] = np.nan
print(iris_2d)

[  8  24  67 103  87  79 138  94  98  53  66  14  34  24 143 107  60  58
 144 137]
[1 2 2 3 0 0 3 1 1 1 3 0 0 3 3 3 3 1 3 1]
[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' nan b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' nan b'Iris-setosa']
 [b'5.8' nan b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' nan b'Iris-setosa']
 [b'5.7' b'3.8' nan b'0.3' b'Iris-setosa']
 [b'5.1' b'3.8' 