### 101 NumPy Exercises for Data Analysis (Python)

### Questions from https://www.machinelearningplus.com/python/101-numpy-exercises-python/


Difficulty Level: L1
Q. Import numpy as np and print the version number.

In [2]:
import numpy as np
print(np.__version__)

2.0.0


Difficulty Level: L1

Q. Create a 1D array of numbers from 0 to 9

In [2]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


Difficulty Level: L1

Q. Create a 3×3 numpy array of all True’s

In [10]:
a = np.full((3,3), True, dtype=bool)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Difficulty Level: L1

Q. Extract all odd numbers from arr

In [18]:
a = np.arange(10)
a = a[a % 2 == 1]
print(a)

[1 3 5 7 9]


Difficulty Level: L1

Q. Replace all odd numbers in arr with -1

Input:

In [14]:
a = np.arange(10)
a[a % 2 == 1] = -1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Difficulty Level: L2

Q. Replace all odd numbers in arr with -1 without changing arr

Input:

In [27]:
a = np.arange(10)
print(a)
b = np.where(a % 2 == 1, -1, a)
print(b)
# c = np.array(b)
# print(c)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Difficulty Level: L1

Q. Convert a 1D array to a 2D array with 2 rows

In [32]:
a = np.arange(10)
a = a.reshape((2, 5))
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Difficulty Level: L2

Q. Stack arrays a and b vertically

In [53]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
# c = np.full((1, 10), 1)[0]
print(a)
print(b)
c = np.vstack([a, b])
print(c)


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Difficulty Level: L2

Q. Stack the arrays a and b horizontally.

Input

In [54]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

c = np.hstack([a, b])
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


Difficulty Level: L2

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

In [58]:
a = np.array([1, 2, 3])

one = np.repeat(a[0], 3)
two = np.repeat(a[1], 3)
three = np.repeat(a[2], 3)

b = np.hstack([one, two, three, a, a, a])
print(b)

c = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(c)


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


Difficulty Level: L2

Q. Get the common items between a and b

Input:

In [63]:
a = np.arange(10)
b = np.arange(5, 10)
c = np.intersect1d(a, b)
print(c)

[5 6 7 8 9]


Difficulty Level: L2

Q. From array a remove all items present in array b
Input:

In [64]:
a = np.arange(10)
b = np.arange(5, 10)
c = np.setdiff1d(a, b)
print(c)

[0 1 2 3 4]


Difficulty Level: L2

Q. Get the positions where elements of a and b match

In [68]:
a = np.arange(10)
b = np.arange(5, 15)
print(a)
print(b)
np.where(a == b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[0 1 2 3 4]


14. Difficulty Level: L2

Q. Get all items between 5 and 10 from a.

Input:

In [80]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

index = np.where((a >= 5) & (a <= 10))
print(a[b])

c = a[(a >=5) & (a <= 10)]
print(c)

[ 6  9 10]
[ 6  9 10]


15. Difficulty Level: L2

Q. Convert the function maxx that works on two scalars, to work on two arrays.

In [9]:
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y


c = np.vectorize(maxx, otypes=[float])
a = np.random.randint(0, 10, 10, dtype=int)
b = np.random.randint(5, 10, 10, dtype=int)
print(a)
print(b)
print(c(a, b))



[3 2 8 1 6 3 9 1 1 0]
[5 7 6 6 7 6 5 8 9 7]
[5. 7. 8. 6. 7. 6. 9. 8. 9. 7.]


16. How to swap two columns in a 2d numpy array?
Difficulty Level: L2

Q. Swap columns 1 and 2 in the array arr.

In [18]:
a = np.random.randint(0, 10, 9, dtype=int)
a = a.reshape((3, -1))
print(a)
print(a[:, [0, 2, 1]])



[[2 0 3]
 [5 8 8]
 [9 6 8]]
[[2 3 0]
 [5 8 8]
 [9 8 6]]


17. How to swap two rows in a 2d numpy array?
Difficulty Level: L2

Q. Swap rows 1 and 2 in the array arr:

In [22]:
a = np.random.randint(0, 9, 9, dtype=int)
a = a.reshape(3, 3)
print(a)
a = a[[0, 2, 1], :]
print(a)

[[8 0 7]
 [8 8 1]
 [1 1 0]]
[[8 0 7]
 [1 1 0]
 [8 8 1]]


18. How to reverse the rows of a 2D array?
Difficulty Level: L2

Q. Reverse the rows of a 2D array arr.

In [31]:
a = np.random.randint(0, 20, 9, dtype=int).reshape(3, 3)
print(a)
a = a[:: -1]
print(a)


[[10  8  1]
 [ 7 17 18]
 [18 12  6]]
[[18 12  6]
 [ 7 17 18]
 [10  8  1]]


19. How to reverse the columns of a 2D array?
Difficulty Level: L2

Q. Reverse the columns of a 2D array arr.

In [34]:
a = np.arange(9).reshape(3, 3)
print(a)
a = a[:, :: -1]
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


20. How to create a 2D array containing random floats between 5 and 10?
Difficulty Level: L2
Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [36]:
a = np.random.uniform(5, 10, size=(5,3))
print(a)

[[7.70934808 8.79737064 9.67666104]
 [7.32756873 9.37922642 7.36714488]
 [7.08288696 9.39102651 5.07460962]
 [8.83385438 7.16089669 7.05689459]
 [7.98133458 7.65311798 8.8891074 ]]
